apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
